spring.application.name=HMBM-Diet-Manager
properties
CopiarEditar
# Dados do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/diet_application_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HikariCP (opcional tuning)
spring.datasource.hikari.maximum-pool-size=10

# JWT   
jwt.secret=${JWT_SECRET}
jwt.expirationMs=3600000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

